services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
      - VITE_WS_URL=ws://backend:5000
    networks:
      - happyseek-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - happyseek-network

  # Database service
  mysql:
    image: mysql:8.0
    container_name: happyseek-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=HappySeek@Root2025
      - MYSQL_DATABASE=crawler
      - MYSQL_USER=crawler
      - MYSQL_PASSWORD=Crawler@2025
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - happyseek-network

networks:
  happyseek-network:
    driver: bridge

volumes:
  mysql_data: